### PR TITLE
Redux Tests

### PR DESCRIPTION
**Pull request by AllenFang**
Use `redux-api-middleware` instead of `redux-thunk`

- [x] reducers
- [x] actions
- [x] redux-api-middleware test

### CODE REVIEW

**Comment by AllenFang** [comment]
@CYBAI  please check  https://github.com/AllenFang/ungit-react/commit/86d55e9a1c7078417c28cf5fdca5f561dac1f969 and https://github.com/AllenFang/ungit-react/commit/0844659dcc8fc172d5f26d5756e9690ee458bc30

I only have this two commit in my fork, and this both commits is for using `fetch` with `redux-fetch-middleware` instead of using `fetch` with `redux-thunk`.

Something need discuss:
1. in the [there](https://github.com/AllenFang/ungit-react/blob/use-fetch-in-middleware/src-react/actions/bootstrap.js#L10), due to those fetch action is not async anymore, but action creator must return an object with `type`(This is rule by calling `bindActionCreator`). So I force return a no operation(aka, `NO_OP`) action. Actually, there's a middleware call [redux-multi](https://github.com/ashaffer/redux-multi) which can help us to return multiple action creator, but it most like out of maintain for a very long time and also have some bug(But I've give a try with `ungit`).

2. `redux-fetch-middleware` is also seems like out of maintain.
3. Using this middleware will force us to use `store.dispatch` in `action`, like [here](https://github.com/AllenFang/ungit-react/blob/use-fetch-in-middleware/src-react/actions/bootstrap.js#L7-L9) and [here](https://github.com/AllenFang/ungit-react/blob/use-fetch-in-middleware/src-react/actions/ungit-config.js#L13)

Please let me know your concern, it's just a experiment and we dont must use it but if we want to use this, I can base this two commits to create another PR.

Thanks

**Comment by AllenFang** [comment]
BTW, The test of reducers are done, please review.

**Comment by CYBAI** [comment]
@AllenFang 

1. About `redux-fetch-middleware`, due to out of maintain, I'm not sure if we can change to [`redux-api-middleware`](https://github.com/agraboso/redux-api-middleware).
2. I'll review this PR in these days; in the meantime, could you help to add `.travis.yml` to trigger the travis?

Thanks.

**Comment by AllenFang** [comment]
It seems a good idea to use `redux-fetch-middleware`, but I think return multi actionCreator and using `store.dispatch` still can't be avoid? I need to check more but I guess this two issues still remain even we use  `redux-fetch-middleware`.

**Review by CYBAI — APPROVED** [review]
Test part LGTM.
Could you help to add `.travis.yml` to trigger testing?

**Comment by CYBAI** [comment]
Merge this PR first, have to fix `TypeError: Cannot read property 'async' of undefined` later.

**Pull request merged**
